language: php

php:
  - 7.1
  - 7.2

sudo: false

before_script:
  - travis_retry composer self-update
  - travis_retry composer require php-coveralls/php-coveralls
  - travis_retry composer install --dev --no-interaction

script:
  - mkdir -p build/logs
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - sh -c 'php vendor/bin/coveralls -v'